# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [116]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [117]:
# Create a 1-dimensional NumPy array using np.array()
one_d = np.array([1,2,3])
# Create a 2-dimensional NumPy array using np.array()
two_d = np.array([[1,2,3],
                 [1,2,3]])
# Create a 3-dimensional Numpy array using np.array()
three_d = np.array([[[1,2,3],
                     [4,5,6],
                     [7,8,9]],
                    [[10,11,12],
                     [13,14,15],
                     [16,17,18]]])


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [118]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
np.shape(one_d),np.ndim(one_d),np.size(one_d),type(one_d)


((3,), 1, 3, numpy.ndarray)

In [119]:
# Attributes of 2-dimensional array
np.shape(two_d),np.ndim(two_d),np.size(two_d),type(two_d)

((2, 3), 2, 6, numpy.ndarray)

In [120]:
# Attributes of 3-dimensional array
np.shape(three_d),np.ndim(three_d),np.size(three_d),type(three_d)

((2, 3, 3), 3, 18, numpy.ndarray)

In [121]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(two_d)
df

0  1  2
0  1  2  3
1  1  2  3

In [122]:
# Create an array of shape (10, 2) with only ones
np.ones([10,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [123]:
# Create an array of shape (7, 2, 3) of only zeros

np.zeros([7,2,3]) 

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [124]:
# Create an array within a range of 0 and 100 with step 3

np.arange(0,101,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [125]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(11, size=(7,2))


array([[ 0,  7],
       [ 3, 10],
       [ 0,  7],
       [ 3,  5],
       [ 7,  3],
       [ 2,  8],
       [ 2,  8]], dtype=int32)

In [126]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.rand(3,5)

array([[0.00506158, 0.16080805, 0.54873379, 0.6918952 , 0.65196126],
       [0.22426931, 0.71217922, 0.23724909, 0.3253997 , 0.74649141],
       [0.6496329 , 0.84922341, 0.65761289, 0.5683086 , 0.09367477]])

In [127]:
# Set the random seed to 42

np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)

np.random.randint(0,10, size= (4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

MY_ANS:-> we fix the seed to 0, so the random numbers are always the same.

In [128]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
array = np.random.randint(1,10, size= (3,7))

# Find the unique numbers in the array you just created
np.unique(array)

array([1, 2, 3, 4, 5, 7, 9], dtype=int32)

In [129]:
# Find the 0'th index of the latest array you created
array[0]


array([9, 1, 3, 7, 4, 9, 3], dtype=int32)

In [130]:
# Get the first 2 rows of latest array you created
array[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]], dtype=int32)

In [131]:
array

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]], dtype=int32)

In [132]:
# Get the first 2 values of the first 2 rows of the latest array
array[:2,:2] 

array([[9, 1],
       [5, 3]], dtype=int32)

In [133]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a4 = np.random.randint(10,size=(3,5))

ones = np.ones((3,5))

print(a4)
ones

[[6 7 2 0 3]
 [1 7 3 1 5]
 [5 9 3 5 1]]


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [134]:
# Add the two arrays together
a4+ones

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [135]:
# Create another array of ones of shape (5, 3)

ones_shape = np.ones((5,3))
ones_shape

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [136]:
# Try add the array of ones and the other most recent array together
ones_shape+a4

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?
My_ANS:-> shape is (5, 3), so we need to reshape it to (3, 5)

In [ ]:
# Create another array of ones of shape (3, 5)
ones = np.ones((3,5))

In [ ]:
# Subtract the new array of ones from the other most recent array
ones-a4 

In [ ]:
# Multiply the ones array with the latest array
ones*a4

In [ ]:
# Take the latest array to the power of 2 using '**'
a4**2

In [ ]:
# Do the same thing with np.square()
np.square(a4)

In [ ]:
# Find the mean of the latest array using np.mean()
np.mean(a4)


In [ ]:
# Find the maximum of the latest array using np.max()
np.max(a4)

In [ ]:
# Find the minimum of the latest array using np.min()
np.min(a4)

In [ ]:
# Find the standard deviation of the latest array
np.std(a4)

In [ ]:
# Find the variance of the latest array
np.var(a4)

In [ ]:
# Reshape the latest array to (3, 5, 1)
a4.reshape(3,5,1)

In [ ]:
# Transpose the latest array
a4.T

What does the transpose do?
My_ANS:-> it transposes the array, so rows become columns and vice versa.

In [ ]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
a1 = np.random.randint(10,size=(3,3))

a2 = np.random.randint(10,size=(3,2))
a1,a2

In [ ]:
# Perform a dot product on the two newest arrays you created
np.dot(a1,a2)

In [ ]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)

a1 = np.random.randint(10,size=(4,3))

a2 = np.random.randint(10,size=(4,3))

a1,a2

In [ ]:
# Perform a dot product on the two newest arrays you created

np.dot(a1,a2)

It doesn't work. How would you fix it?
My_ANS:-> we need to reshape it to (3, 4) first.

we can use the reshape method to change the shape of an array.
The reshape method takes a tuple as an argument, which specifies the new shape of the array.
The new shape must have the same number of elements as the original array.  
For example, if we have an array with shape (3, 5), we can reshape it to (5, 3) or (15, 1), but not to (4, 4).
The reshape method returns a new array with the specified shape, but it does not modify the original array.
The original array remains unchanged.
The reshape method can be used to change the shape of an array without changing its data.
the code will be:
```python
import numpy as np
np.random.seed(0)
a = np.random.randint(1, 10, size=(5, 3))
a = a.reshape(3, 5)
a = a.T
result = np.dot(a, a)  # Perform the dot product
result
```

In [ ]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(a1,a2.T)

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [137]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables

a1 = np.random.randint(10,size=(5,3))
a2 = np.random.randint(10,size=(5,3))
a1,a2

(array([[9, 1, 9],
        [3, 7, 6],
        [8, 7, 4],
        [1, 4, 7],
        [9, 8, 8]], dtype=int32),
 array([[0, 8, 6],
        [8, 7, 0],
        [7, 7, 2],
        [0, 7, 2],
        [2, 0, 4]], dtype=int32))

In [139]:
# Compare the two arrays with '>'
a1>a2

array([[ True, False,  True],
       [False, False,  True],
       [ True, False,  True],
       [ True, False,  True],
       [ True,  True,  True]])

What happens when you compare the arrays with `>`?

In [140]:
# Compare the two arrays with '>='
a1>=a2

array([[ True, False,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [ True, False,  True],
       [ True,  True,  True]])

In [141]:
# Find which elements of the first array are greater than 7
a1>7

array([[ True, False,  True],
       [False, False, False],
       [ True, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [142]:
# Which parts of each array are equal? (try using '==')

a1==a2

array([[False, False, False],
       [False,  True, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False]])

In [147]:
# Sort one of the arrays you just created in ascending order
np.sort(a1)

array([[1, 9, 9],
       [3, 6, 7],
       [4, 7, 8],
       [1, 4, 7],
       [8, 8, 9]], dtype=int32)

In [148]:
# Sort the indexes of one of the arrays you just created
np.argsort(a1)

array([[1, 0, 2],
       [0, 2, 1],
       [2, 1, 0],
       [0, 1, 2],
       [1, 2, 0]])

In [152]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a1)

np.int64(0)

In [153]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a1)

np.int64(1)

In [154]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(a1,axis=1)

array([0, 1, 0, 2, 0])

In [158]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(a1,axis=0)

array([3, 0, 2])

In [172]:
# Create an array of normally distributed random numbers
np.random.randn(3,2)

array([[ 0.19059871,  0.60697571],
       [-0.34890118,  0.60612936],
       [-1.94422959,  0.33639876]])

In [181]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.random.randint(1,100,10)

array([66, 32, 87, 63, 86, 51, 25, 58, 63, 62], dtype=int32)

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.